export const dummyWords = [
  'Accio',
  'Alohomora',
  'Avada Kedavra',
  'Expecto Patronum',
  'Expelliarmus',
  'Imperio',
  'Lumos',
  'Nox',
  'Obliviate',
  'Wingardium Leviosa',
  'Stupefy',
  'Crucio',
  'Protego',
  'Aguamenti',
  'Lumos Maxima',
  'Aparecium',
  'Diffindo',
  'Morsmordre',
  'Riddikulus',
  'Levicorpus',
  'Expulso',
  'Incarcerous',
  'Reducto',
  'Serpensortia',
  'Avis',
  'Silencio',
  'Locomotor',
  'Muffliato',
  'Mobilicorpus',
  'Reparo',
  'Impedimenta',
  'Sonorus',
  'Petrificus Totalus',
  'Legilimens',
  'Crucio',
  'Incendio',
  'Aqua Eructo',
  'Baubillious',
  'Confringo',
  'Furnunculus',
  'Glacius',
  'Incarcerous',
  'Lumos Solem',
  'Oblitus',
  'Peskipiksi',
  'Protego Totalum',
  'Reducio',
  'Rennervate',
  'Serpeverda',
  'Stupefy',
  'Tarantallegra',
  'Tergeo',
  'Ventus',
  'Vulnera Sanentur',
  'Quietus',
];
